In [338]:
# 데이터 읽기
import numpy as np
import pandas as pd
dis_pop = pd.read_csv('data/주민등록인구집계현황.csv', encoding='euc-kr')
dis_pop.head()

,연도,월,행정구역구분명,행정구역명,총 인구수,0~9세,10~19세,20~29세,30~39세,40~49세,...,10~19세 (여),20~29세 (여),30~39세 (여),40~49세 (여),50~59세 (여),60~69세 (여),70~79세 (여),80~89세 (여),90~99세 (여),100세 이상 (여)
0,2022,12,도,경기도,13589432,1040954,1327726,1737291,1882300,2284603,...,647283,821150,904073,1121889,1133428,878494,437251,252711,44184,1369
1,2022,12,시군,경기도 가평군,62197,2930,4463,5929,5397,7589,...,2186,2503,2433,3525,5090,6439,3653,2408,411,13
2,2022,12,읍면동,경기도 가평군 가평읍,19555,1020,1673,2094,1795,2630,...,778,937,848,1244,1583,1805,1054,739,126,6
3,2022,12,읍면동,경기도 가평군 북면,3815,108,174,230,223,357,...,93,87,99,154,290,511,294,216,39,1
4,2022,12,읍면동,경기도 가평군 상면,5669,140,259,482,389,533,...,112,151,166,240,515,737,389,244,39,0

In [339]:
# 결측치 확인
dis_pop.isna().sum().sum()

0

In [340]:
# 가임기 여성 인구수, 60세 이상 노령인구
dis_pop['가임기 여성 인구수'] = dis_pop['10~19세 (여)'] + dis_pop['20~29세 (여)']
dis_pop['60세 이상 노령인구'] = dis_pop['60~69세'] + dis_pop['70~79세'] + dis_pop['80~89세'] + dis_pop['90~99세'] + dis_pop['100세 이상']

In [341]:
dis_pop['가임기 여성 인구수']

0      1468433
1         4689
2         1715
3          180
4          263
        ...
615        512
616       9692
617       2420
618          0
619          0
Name: 가임기 여성 인구수, Length: 620, dtype: int64

In [342]:
dis_pop['60세 이상 노령인구']

0      3023136
1        24979
2         6953
3         2058
4         2792
        ...
615       3725
616      12478
617       5673
618          0
619          0
Name: 60세 이상 노령인구, Length: 620, dtype: int64

In [343]:
# 인구 소멸 비율
dis_pop['인구소멸 비율'] = dis_pop['가임기 여성 인구수'] / dis_pop['60세 이상 노령인구']

In [344]:
dis_pop['인구소멸 비율']

0      0.485732
1      0.187718
2      0.246656
3      0.087464
4      0.094198
         ...
615    0.137450
616    0.776727
617    0.426582
618         NaN
619         NaN
Name: 인구소멸 비율, Length: 620, dtype: float64

In [345]:
# 기초자치단체
dis_pop['기초자치단체'] = dis_pop['행정구역구분명']

In [346]:
dis_pop = dis_pop['행정구역명,인구소멸 비율,기초자치단체'.split(',')]
dis_pop

             행정구역명   인구소멸 비율 기초자치단체
0            경기도    0.485732      도
1         경기도 가평군   0.187718     시군
2      경기도 가평군 가평읍  0.246656    읍면동
3       경기도 가평군 북면  0.087464    읍면동
4       경기도 가평군 상면  0.094198    읍면동
..             ...       ...    ...
615    경기도 화성시 팔탄면  0.137450    읍면동
616    경기도 화성시 향남읍  0.776727    읍면동
617    경기도 화성시 화산동  0.426582    읍면동
618  경기도 화성시동부출장소        NaN    읍면동
619  경기도 화성시동탄출장소        NaN    읍면동

[620 rows x 3 columns]

In [347]:
# 기초자치단체 읍면동 제거, 내림차순
index1 = dis_pop[dis_pop['기초자치단체'] == '읍면동'].index
dis_pop.drop(index1).sort_values(['인구소멸 비율']).head(10)

            행정구역명   인구소멸 비율 기초자치단체
1        경기도 가평군   0.187718     시군
417      경기도 연천군   0.187908     시군
391      경기도 양평군   0.192583     시군
404      경기도 여주시   0.252195     시군
558      경기도 포천시   0.259271     시군
156     경기도 동두천시   0.311098     시군
328      경기도 안성시   0.357350     시군
363  경기도 안양시 만안구   0.368266      구
218  경기도 성남시 중원구   0.376513      구
200  경기도 성남시 수정구   0.379392      구